id: P007871
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5623
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་དང་བཻ་རོ་ཙ་ནའི་རྣམ་ཐར་སོགས།
  author: ''
  volumes:
    4a4a3c369eee4684bce85c8ec7413e2d:
      image_group_id: I1KG5687
      title: ''
      volume_number: 1
      total_pages: 162
ebook_metadata:
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་དང་བཻ་རོ་ཙ་ནའི་རྣམ་ཐར་སོགས།
  author: ''
  sku: P007871
  cover: cover.jpg
  layers:
  - pagination
