id: P007871
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:20.780648
source_metadata:
  id: bdr:W1KG5623
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་དང་བཻ་རོ་ཙ་ནའི་རྣམ་ཐར་སོགས།
  author: ''
  volumes:
    1456b181170d4a9884fa25b0a717a615:
      image_group_id: I1KG5687
      title: Volume 1 of mkha' 'gro ye shes mtsho rgyal dang bai ro tsa na'i rnam
        thar
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
